theme: just-the-docs
title: Sharo Aho Offline
description: Sharo Aho Offline Specification Document
mermaid:
  version: 9.1.3
aux_links:
  'Sharo Aho Offline on GitHub':
    - https://github.com/japan-expert-force/sharo-aho-offline
aux_links_new_tab: true
gh_edit_link: true
gh_edit_link_text: Edit this page on GitHub.
gh_edit_repository: https://github.com/japan-expert-force/sharo-aho-offline
gh_edit_branch: master
gh_edit_view_mode: tree
enable_copy_code_button: true
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
